site_name: MSScore 文档
site_description: MSScore framework, high performance, easy to learn, fast to code, ready for production
site_url: https://msscore.readthedocs.io/
theme:
  name: material
  logo: https://fastapi.tiangolo.com/img/icon-white.svg
  favicon: https://fastapi.tiangolo.com/img/favicon.png
  language: zh
  features:
    - content.code.annotate
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_name: jindaxiang/msscore
repo_url: https://github.com/jindaxiang/msscore
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences